[package]
name = "naze-runtime"
version.workspace = true
edition.workspace = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
naze-ir = { path = "../naze-ir" }
naze-layout = { path = "../naze-layout" }
naze-renderer = { path = "../naze-renderer" }
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
    "Window",
    "Document",
    "Element",
    "HtmlElement",
    "HtmlInputElement",
    "HtmlTextAreaElement",
    "HtmlDivElement",
    "HtmlBodyElement",
    "MouseEvent",
    "WheelEvent",
    "KeyboardEvent",
    "Event",
    "EventTarget",
    "HtmlCanvasElement",
    "CssStyleDeclaration",
    "Location",
    "HashChangeEvent",
    "Node",
    "console",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Headers",
    "Performance",
    "Navigator",
    "Clipboard",
    "WebSocket",
    "MessageEvent",
    "CloseEvent",
    "EventSource",
    "EventSourceInit",
    "File",
    "FileList",
    "FileReader",
    "Blob",
    "Storage",
    "FormData",
    "History",
    "PopStateEvent",
    "Url",
    "UrlSearchParams",
    "TouchEvent",
    "TouchList",
    "Touch",
    "DomRect",
    "Notification",
    "NotificationOptions",
    "NotificationPermission",
    "Geolocation",
    "Position",
    "Coordinates",
    "PositionError",
    "PositionOptions",
    "DeviceMotionEvent",
] }
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"
